### ISSUE TITLE
 I18n::InvalidLocale in Spree::Admin::OrdersController#index

### ISSUE THREAD

**Issue by zhenbeiju** [spree-contrib/spree_i18n#504]
I use 2-2-stable branch ,
I meet this error when i visit "http://127.0.0.1:3000/admin"

My config is :
```
 config.time_zone = 'Beijing'


 config.i18n.default_locale = :'zh-CN'
```
error messages is:
```
I18n::InvalidLocale in Spree::Admin::OrdersController#index
:zh is not a valid locale

Rails.root: /Users/linzhang/RubymineProjects/spree/sandbox

Application Trace | Framework Trace | Full Trace
i18n (0.6.9) lib/i18n.rb:288:in `enforce_available_locales!'
i18n (0.6.9) lib/i18n.rb:150:in `translate'
i18n (0.6.9) lib/i18n/backend/base.rb:119:in `block in resolve'
i18n (0.6.9) lib/i18n/backend/base.rb:116:in `catch'
i18n (0.6.9) lib/i18n/backend/base.rb:116:in `resolve'
i18n (0.6.9) lib/i18n/backend/base.rb:103:in `block in default'
i18n (0.6.9) lib/i18n/backend/base.rb:102:in `each'
i18n (0.6.9) lib/i18n/backend/base.rb:102:in `default'
i18n (0.6.9) lib/i18n/backend/base.rb:34:in `translate'
i18n (0.6.9) lib/i18n/backend/chain.rb:46:in `block (2 levels) in translate'
i18n (0.6.9) lib/i18n/backend/chain.rb:44:in `catch'
i18n (0.6.9) lib/i18n/backend/chain.rb:44:in `block in translate'
i18n (0.6.9) lib/i18n/backend/chain.rb:43:in `each'
i18n (0.6.9) lib/i18n/backend/chain.rb:43:in `translate'
i18n (0.6.9) lib/i18n/backend/fallbacks.rb:44:in `block (2 levels) in translate'
i18n (0.6.9) lib/i18n/backend/fallbacks.rb:43:in `catch'
i18n (0.6.9) lib/i18n/backend/fallbacks.rb:43:in `block in translate'
i18n (0.6.9) lib/i18n/backend/fallbacks.rb:42:in `each'
i18n (0.6.9) lib/i18n/backend/fallbacks.rb:42:in `translate'
i18n (0.6.9) lib/i18n.rb:157:in `block in translate'
i18n (0.6.9) lib/i18n.rb:153:in `catch'
i18n (0.6.9) lib/i18n.rb:153:in `translate'
cancan (1.6.10) lib/cancan/ability.rb:217:in `unauthorized_message'
cancan (1.6.10) lib/cancan/ability.rb:207:in `authorize!'
cancan (1.6.10) lib/cancan/controller_additions.rb:338:in `authorize!'
/Users/linzhang/RubymineProjects/spree/backend/app/controllers/spree/admin/base_controller.rb:25:in `authorize_admin'
activesupport (4.0.13) lib/active_support/callbacks.rb:447:in `_run__2554612074576225022__process_action__callbacks'
activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.13) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.13) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.13) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.0.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.13) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.13) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.13) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.13) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.13) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:676:in `call'
railties (4.0.13) lib/rails/engine.rb:511:in `call'
railties (4.0.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:676:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.13) lib/active_record/migration.rb:373:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__3491257190276076764__call__callbacks'
activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.0.13) lib/rails/engine.rb:511:in `call'
railties (4.0.13) lib/rails/application.rb:97:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/Users/linzhang/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/linzhang/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/linzhang/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

```

**Comment by futhr** [comment]
Hi @zhenbeiju , does it work with `zh-TW`?

**Comment by zhenbeiju** [comment]
@futhr  I have try like you say, doesn't work too, I see the same issue here https://github.com/rails/rails/issues/13164
seems  solve need use  i18n@master, but spree 2-2-stable define i18n (＝0.6.9) ，

so, I change to use 2-4-stable, every thing fine

**Comment by futhr** [comment]
The solution from the Rails issue was to add this config: `config.i18n.enforce_available_locales = false`

**Comment by zhenbeiju** [comment]
Thank you
