### ISSUE TITLE
RailsI18n Pluralizations comparison of Symbol with 0 failed (with french :fr at least)

### ISSUE THREAD

**Issue by fzingg** [spree-contrib/spree_i18n#505]
Spree Admin/products and admin/orders raise an error because of these line in fr.yml : 

models:
      ...
      spree/order:
        one: Commande
        other: Commandes
     .....
      spree/product:
        one: Produit
        other: Produits

log : 

rails-i18n (4.0.3) lib/rails_i18n/common_pluralizations/one_upto_two_other.rb

module RailsI18n
  module Pluralization
    module OneUptoTwoOther
      def self.rule
->        lambda { |n| n >= 0 && n < 2 ? :one : :other }
      end

**Comment by futhr** [comment]
Hi @fzingg, please follow steps in: https://github.com/spree-contrib/spree_i18n/blob/master/CONTRIBUTING.md#filing-an-issue

**Comment by fzingg** [comment]
**Rails 4.1.8** - **Spree 3.0.0beta** Last commit - **Spre_I18n** Last commit

Issue : 
when access /admin/products?locale=en-GB or /admin/products?locale=zh-CN OK
when access /admin/products?locale=fr error : 

**comparison of Symbol with 0 failed**

```
block in rulerails-i18n (4.0.3) lib/rails_i18n/common_pluralizations/one_upto_two_other.rb

module RailsI18n
  module Pluralization
    module OneUptoTwoOther
      def self.rule
->        lambda { |n| n >= 0 && n < 2 ? :one : :other }
      end
```

It seems there's a problem with fr.yml : 

```
models:
  spree/product:
    one: Produit
    other: Produits
```

FULL TRACE : 

```
I, [2015-01-24T13:07:08.220678 #31469]  INFO -- : Started GET "/admin/products?locale=fr" for 127.0.0.1 at 2015-01-24 13:07:08 +0800
I, [2015-01-24T13:07:08.271231 #31469]  INFO -- : Processing by Spree::Admin::ProductsController#index as HTML
I, [2015-01-24T13:07:08.271695 #31469]  INFO -- :   Parameters: {"locale"=>"fr"}
D, [2015-01-24T13:07:08.275902 #31469] DEBUG -- :   User Load (0.6ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY id ASC LIMIT 1
D, [2015-01-24T13:07:08.278231 #31469] DEBUG -- :   Avatar Load (0.4ms)  SELECT "avatars".* FROM "avatars"  WHERE "avatars"."avatarable_type" = 'User' AND "avatars"."avatarable_id" IN (1)
D, [2015-01-24T13:07:08.281378 #31469] DEBUG -- :    (0.3ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = $1 AND "spree_roles"."name" = 'admin'  [["user_id", 1]]
I, [2015-01-24T13:07:08.403033 #31469]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/spree-7d63654f7116/backend/app/views/spree/admin/products/index.html.erb within spree/layouts/admin (44.8ms)
I, [2015-01-24T13:07:08.403416 #31469]  INFO -- : Completed 500 Internal Server Error in 131ms
F, [2015-01-24T13:07:08.431358 #31469] FATAL -- : 
ArgumentError - comparison of Symbol with 0 failed:
  rails-i18n (4.0.3) lib/rails_i18n/common_pluralizations/one_upto_two_other.rb:7:in `block in rule'
  i18n (0.7.0) lib/i18n/backend/pluralization.rb:34:in `pluralize'
  i18n (0.7.0) lib/i18n/backend/base.rb:40:in `translate'
  i18n (0.7.0) lib/i18n/backend/chain.rb:46:in `block (2 levels) in translate'
  i18n (0.7.0) lib/i18n/backend/chain.rb:44:in `block in translate'
  i18n (0.7.0) lib/i18n/backend/chain.rb:43:in `translate'
  i18n (0.7.0) lib/i18n/backend/fallbacks.rb:45:in `block (2 levels) in translate'
  i18n (0.7.0) lib/i18n/backend/fallbacks.rb:44:in `block in translate'
  i18n (0.7.0) lib/i18n/backend/fallbacks.rb:42:in `translate'
  i18n (0.7.0) lib/i18n.rb:158:in `block in translate'
  i18n (0.7.0) lib/i18n.rb:154:in `translate'
  activemodel (4.1.8) lib/active_model/naming.rb:187:in `human'
   () home/fcooker/rails/spreetest/vendor/bundle/ruby/2.2.0/bundler/gems/spree-7d63654f7116/backend/app/views/spree/admin/products/index.html.erb:2:in `block in _79c16301c1140711ab85e4229c5c7207'
  actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:152:in `content_for'
   () home/fcooker/rails/spreetest/vendor/bundle/ruby/2.2.0/bundler/gems/spree-7d63654f7116/backend/app/views/spree/admin/products/index.html.erb:1:in `_79c16301c1140711ab85e4229c5c7207'
  actionview (4.1.8) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.8) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.8) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.8) lib/action_view/template.rb:143:in `render'
  deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
  actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.8) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.8) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.8) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.8) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.8) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.8) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.8) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.8) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.8) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.8) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.8) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.8) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/fcooker/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.1.8) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:40:in `render'
  remotipart (1.2.1) lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
  actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.1.8) lib/action_controller/metal/responder.rb:238:in `default_render'
  actionpack (4.1.8) lib/action_controller/metal/responder.rb:165:in `to_html'
   () home/fcooker/rails/spreetest/vendor/bundle/ruby/2.2.0/bundler/gems/spree-7d63654f7116/core/lib/spree/responder.rb:19:in `to_html'
  actionpack (4.1.8) lib/action_controller/metal/responder.rb:158:in `respond'
  actionpack (4.1.8) lib/action_controller/metal/responder.rb:151:in `call'
   () home/fcooker/rails/spreetest/vendor/bundle/ruby/2.2.0/bundler/gems/spree-7d63654f7116/core/lib/spree/core/controller_helpers/respond_with.rb:23:in `respond_with'
   () home/fcooker/rails/spreetest/vendor/bundle/ruby/2.2.0/bundler/gems/spree-7d63654f7116/backend/app/controllers/spree/admin/products_controller.rb:18:in `index'
  actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  bullet (4.14.2) lib/bullet/rack.rb:10:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.4) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.8) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.8) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.8) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.8) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.8) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'
```

**GEMFILE : **
```
	 source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'

gem 'rails-observers', '0.1.2'
#gem 'actionpack-action_caching', '1.1.1'
#gem 'actionpack-page_caching', '1.0.2'

gem 'mail_form', '1.5.0'

# Use postgresql as the database for Active Record
gem 'pg', '0.18.1'

# Use SCSS for stylesheets
gem 'sass-rails', '4.0.3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '2.7.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '4.1.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.1.2'
gem 'jquery-ui-rails', '5.0.3'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '2.5.3'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '2.2.6'

group :doc do
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', require: false
end

gem "devise", '3.4.1'
gem "cancancan", '1.9.2'
gem "rolify", '3.5.1'
gem "gon", '5.2.3'

gem "routing-filter", '0.4.0.pre'

gem 'compass-rails', '2.0.0'
gem 'foundation-rails', '5.4.5.0'
gem 'font-awesome-sass', '4.2.2'

gem 'jquery-fileupload-rails', '0.4.2'
gem "remotipart", '1.2.1'

gem 'paperclip', '4.2.1'
gem 'image_optim', '0.20.2'
gem 'image_optim_pack'
gem 'paperclip-optimizer', '1.0.3'
gem 'acts_as_list', '0.5.0'
#gem 'routing-filter'
gem 'globalize', '4.0.3'

gem 'spree', github: 'spree/spree', branch: 'master'
gem 'spree_i18n', :github => 'spree/spree_i18n'

gem 'thin' , group: :development
gem 'better_errors', group: :development
gem 'binding_of_caller', group: :development
gem 'quiet_assets' , group: :development
gem 'bullet', group: :development
#gem 'meta_request', group: :development

gem 'dalli', '2.7.2'
gem 'piwik_analytics', '1.0.2'

gem 'capistrano', '3.3.5'
gem 'capistrano-bundler', '1.1.3'
gem 'capistrano-rails', '1.1.2'
gem 'capistrano-rbenv', github: "capistrano/rbenv"
```

**Comment by adoptanoob** [comment]
I have the same problem, did you manage to fix this? Thanks

**Comment by adoptanoob** [comment]
So I have found something interesting. For example in backend/app/views/spree/admin/products/index.html.erb
```
<% content_for :page_title do %>
  <%= Spree::Order.model_name.human(count: :many) %>
<% end %>
```
Changing :many to 2 solved the issue.
Same problem occurs with other pages in the admin section.

I think it is not the recommended way though, what could I possibly be missing?
Thanks

**Comment by adoptanoob** [comment]
I think this issue has been solved by this [commit](https://github.com/JDutil/spree/commit/fd0b057e956490500b5295777947f080c07b1ed9)

I bundle update(d) and it is all working nicely now.
I suggest this issue to be closed.
