### ISSUE TITLE
Strange error on db:schema:load to empty db with installed spree_i18n.

### ISSUE THREAD

**Issue by romul** [spree-contrib/spree_i18n#512]
`$ bundle exec rake db:schema:load --trace`
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "spree_option_types" does not exist
LINE 5:                WHERE a.attrelid = '"spree_option_types"'::re...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"spree_option_types"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attributes.rb:91:in `columns'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attributes.rb:96:in `columns_hash'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:66:in `serializer_for_attribute'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:54:in `enable_serializable_attribute'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:32:in `block in allow_translation_of_attributes'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:30:in `each'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:30:in `allow_translation_of_attributes'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:13:in `translates'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree_i18n-df92012eead2/app/models/spree/option_type_decorator.rb:3:in `block in <module:Spree>'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree_i18n-df92012eead2/app/models/spree/option_type_decorator.rb:2:in `class_eval'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree_i18n-df92012eead2/app/models/spree/option_type_decorator.rb:2:in `<module:Spree>'
```

That's not strange by itself. But it's strange, that only OptionType is affected. 
So after https://github.com/romul/spree_i18n/commit/88daa70209e215d0d187cd29e651bae843edcbb5   `db:schema:load` works like a charm. Any thoughts?

**Comment by JDutil** [comment]
You need to update to globalize 5.0.1 I fixed this with https://github.com/spree-contrib/spree_i18n/commit/d44f146caa6c082c5779e95d178916e5684c366e
