### ISSUE TITLE
undefined method `create_translation_table!'

### ISSUE THREAD

**Issue by mmintel** [spree-contrib/spree_i18n#633]
Hi there,

this error appears after I am trying to run "rake db:migrate" on my server.. but somehow I don't get any error on my local machine.

I am not sure if this is related to spree_i18n, but I didn't install anything else for translations. Do you have an idea where this comes from? What can I do to fix it?

```BASH
Migrating to AddTranslationsToStore (20150602075811)
   (0.5ms)  BEGIN
== 20150602075811 AddTranslationsToStore: migrating ===========================
-- table_exists?(:spree_store_translations)
   -> 0.0012s
   (0.7ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `create_translation_table!' for #<Class:0x007f4aa3ac02e8>/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/app/db/migrate/20150602075811_add_translations_to_store.spree_i18n.rb:6:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:609:in `exec_migration'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `create_translation_table!' for #<Class:0x007f4aa3ac02e8>
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/app/db/migrate/20150602075811_add_translations_to_store.spree_i18n.rb:6:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:609:in `exec_migration'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by alepore** [comment]
which version of spree/i18n are you using?

**Comment by mmintel** [comment]
this error magically disappeared after rebooting the digital ocean droplet.. don't ask me why, I don't understand this! :(

**Comment by alepore** [comment]
maybe you didn't restart the app and old code was running?
that error is usually raise when the model doesn't include the globalize stuff like `translate`

**Comment by mmintel** [comment]
Now this happens again and I don't even understand why this came up again..
This file is causing the error:
```RUBY
# This migration comes from spree_i18n (originally 20150323210949)
class AddTranslationsToStore < ActiveRecord::Migration
  def up
    unless table_exists?(:spree_store_translations)
      params = { name: :string, meta_description: :text, meta_keywords: :text, seo_title: :string }
      Spree::Store.create_translation_table!(params, { migrate_data: true })
    end
  end

  def down
    Spree::Store.drop_translation_table! migrate_data: true
  end
end
```

And thats the Gemfile.lock

```
GIT
  remote: git://github.com/spree-contrib/better_spree_paypal_express.git
  revision: 526d7f4f5bb9074b41b8d6ff38c47d01612ededf
  branch: 3-0-stable
  specs:
    spree_paypal_express (3.0.0)
      paypal-sdk-merchant (= 1.106.1)
      spree_core (~> 3.0.0)

GIT
  remote: git://github.com/spree-contrib/spree_i18n.git
  revision: d31cd8c29f3035886db8468f93b5d4d2f96a6ad4
  branch: 3-0-stable
  specs:
    spree_i18n (3.0.0)
      friendly_id-globalize
      globalize (~> 5.0.1)
      i18n_data (~> 0.7.0)
      kaminari-i18n (~> 0.3.2)
      rails-i18n (~> 4.0.1)
      spree_core (~> 3.0.4)

GIT
  remote: git://github.com/spree-contrib/spree_mail_settings.git
  revision: 99af7e4a137ac76fe4e93b1c8e5a38d81583904c
  branch: 3-0-stable
  specs:
    spree_mail_settings (2.2.0)
      spree_backend (~> 3.0.0)

GIT
  remote: git://github.com/spree-contrib/spree_print_invoice.git
  revision: a4b8acfcaedf0448e69a448850dfd4d00425e40d
  branch: 3-0-stable
  specs:
    spree_print_invoice (3.0.0.beta)
      prawn (~> 1.0.0)
      spree_core (~> 3.0.0)

GIT
  remote: git://github.com/spree-contrib/spree_static_content.git
  revision: d39bb33ffc67041e87800d66d0fd43cfea67373c
  branch: 3-0-stable
  specs:
    spree_static_content (2.3.0)
      spree_core (~> 3.0.0)

GIT
  remote: git://github.com/spree/spree.git
  revision: 4ffdaa8492a7edd68646ee66874cb097835c05aa
  branch: 3-0-stable
  specs:
    spree (3.0.5.beta)
      spree_api (= 3.0.5.beta)
      spree_backend (= 3.0.5.beta)
      spree_cmd (= 3.0.5.beta)
      spree_core (= 3.0.5.beta)
      spree_frontend (= 3.0.5.beta)
      spree_sample (= 3.0.5.beta)
    spree_api (3.0.5.beta)
      rabl (~> 0.11.6)
      spree_core (= 3.0.5.beta)
      versioncake (~> 2.3.1)
    spree_backend (3.0.5.beta)
      bootstrap-sass (~> 3.3.1)
      jquery-rails (~> 4.0.3)
      jquery-ui-rails (~> 5.0.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.0.5.beta)
      spree_core (= 3.0.5.beta)
      sprockets-rails (~> 2.2)
    spree_cmd (3.0.5.beta)
      thor (~> 0.14)
    spree_core (3.0.5.beta)
      activemerchant (~> 1.47.0)
      acts_as_list (~> 0.6)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 1.16)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      json (~> 1.7)
      kaminari (~> 0.15, >= 0.15.1)
      monetize (~> 1.1)
      paperclip (~> 4.2.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.2.2)
      ransack (~> 1.4.1)
      responders
      state_machines-activerecord (~> 0.2)
      stringex
      truncate_html (= 0.9.2)
      twitter_cldr (~> 3.0)
    spree_frontend (3.0.5.beta)
      bootstrap-sass (~> 3.3.1)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 4.0.3)
      spree_api (= 3.0.5.beta)
      spree_core (= 3.0.5.beta)
      sprockets-rails (~> 2.2)
    spree_sample (3.0.5.beta)
      spree_core (= 3.0.5.beta)

GIT
  remote: git://github.com/spree/spree_auth_devise.git
  revision: 7b24ad16239367dc15f96a80cc2a954a822cc6af
  branch: 3-0-stable
  specs:
    spree_auth_devise (3.0.0)
      devise (~> 3.4.1)
      devise-encryptable (= 0.1.2)
      json
      multi_json
      spree_core (~> 3.0.0)

GIT
  remote: git://github.com/spree/spree_gateway.git
  revision: 7301dc7c84c05b46427bf5003eda13ca64a48d7c
  branch: 3-0-stable
  specs:
    spree_gateway (3.0.0.beta)
      spree_core (~> 3.0.0)

GIT
  remote: https://github.com/aleks/spree_better_terms_and_conditions.git
  revision: db2a6f5653ba6e0ddf7ba782ebb1b9006b46ddfe
  branch: master
  specs:
    spree_better_terms_and_conditions (2.2.1)
      spree_core (>= 2.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.1)
    actionmailer (4.2.2)
      actionpack (= 4.2.2)
      actionview (= 4.2.2)
      activejob (= 4.2.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.2)
      actionview (= 4.2.2)
      activesupport (= 4.2.2)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.2)
      activesupport (= 4.2.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.2)
      activesupport (= 4.2.2)
      globalid (>= 0.3.0)
    activemerchant (1.47.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (4.2.2)
      activesupport (= 4.2.2)
      builder (~> 3.1)
    activerecord (4.2.2)
      activemodel (= 4.2.2)
      activesupport (= 4.2.2)
      arel (~> 6.0)
    activesupport (4.2.2)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_list (0.7.2)
      activerecord (>= 3.0)
    addressable (2.3.8)
    arel (6.0.3)
    asset_sync (1.1.0)
      activemodel
      fog (>= 1.8.0)
      unf
    autoprefixer-rails (6.0.3)
      execjs
      json
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    aws-sdk-v1 (1.66.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)
    bower (0.0.5)
      multi_json
    braintree (2.48.1)
      builder (>= 2.0.0)
    builder (3.2.2)
    byebug (6.0.2)
    camertron-eprun (1.1.0)
    cancancan (1.10.1)
    canonical-rails (0.0.11)
      rails (>= 3.1, < 5.0)
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    cldr-plurals-runtime-rb (1.0.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorize (0.7.7)
    css_parser (1.3.6)
      addressable
    debug_inspector (0.0.2)
    deface (1.0.1)
      colorize (>= 0.5.8)
      nokogiri (~> 1.6.0)
      polyglot
      rails (>= 3.1)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    erubis (2.7.0)
    excon (0.45.4)
    execjs (2.6.0)
    ffaker (1.32.1)
    figaro (1.1.1)
      thor (~> 0.14)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.34.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (>= 0.0.2)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.7.6)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.9.0)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.32.1)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-dynect (0.0.2)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.0.7)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.3.1)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (0.4.7)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-rails (4.4.0.0)
      railties (>= 3.2, < 5.0)
    formatador (0.2.5)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    friendly_id-globalize (1.0.0.alpha2)
      friendly_id (~> 5.1.0, < 6.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    globalize (5.0.1)
      activemodel (>= 4.2.0, < 4.3)
      activerecord (>= 4.2.0, < 4.3)
    headjs-rails (0.4.2)
      rails (>= 3.0.0)
    highline (1.6.21)
    htmlcompressor (0.3.0)
    htmlentities (4.3.4)
    i18n (0.7.0)
    i18n_data (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.0)
    jbuilder (2.3.1)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kaminari-i18n (0.3.2)
      kaminari
      rails
    kgio (2.10.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mandrill-api (1.0.53)
      excon (>= 0.16.0, < 1.0)
      json (>= 1.7.7, < 2.0)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.0)
    monetize (1.3.1)
      money (~> 6.6)
    money (6.6.1)
      i18n (>= 0.6.4, <= 0.7.0)
    multi_json (1.11.2)
    mysql2 (0.4.1)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    orm_adapter (0.5.0)
    paperclip (4.2.4)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
    paranoia (2.1.3)
      activerecord (~> 4.0)
    passenger (5.0.18)
      rack
      rake (>= 0.8.1)
    paypal-sdk-core (0.2.10)
      multi_json (~> 1.0)
      xml-simple
    paypal-sdk-merchant (1.106.1)
      paypal-sdk-core (~> 0.2.3)
    pdf-core (0.2.5)
    pg (0.18.3)
    polyamorous (1.2.0)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    prawn (1.0.0)
      pdf-core (~> 0.2.2)
      ttfunk (~> 1.1.1)
    premailer (1.8.6)
      css_parser (>= 1.3.6)
      htmlentities (>= 4.0.0)
    premailer-rails (1.8.2)
      actionmailer (>= 3, < 5)
      premailer (~> 1.7, >= 1.7.9)
    rabl (0.11.6)
      activesupport (>= 2.3.14)
    rack (1.6.4)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-zippy (3.0.1)
    rails (4.2.2)
      actionmailer (= 4.2.2)
      actionpack (= 4.2.2)
      actionview (= 4.2.2)
      activejob (= 4.2.2)
      activemodel (= 4.2.2)
      activerecord (= 4.2.2)
      activesupport (= 4.2.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.2)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails-i18n (4.0.5)
      i18n (~> 0.6)
      railties (~> 4.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.4)
    railties (4.2.2)
      actionpack (= 4.2.2)
      activesupport (= 4.2.2)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rdoc (4.2.0)
      json (~> 1.4)
    redcarpet (3.3.2)
    respond-rails (1.0.1)
      railties (>= 3.1.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    sass (3.4.18)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    spring (1.4.0)
    sprockets (3.3.4)
      rack (~> 1.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    state_machines (0.4.0)
    state_machines-activemodel (0.3.0)
      activemodel (~> 4.1)
      state_machines (>= 0.4.0)
    state_machines-activerecord (0.3.0)
      activerecord (~> 4.1)
      state_machines-activemodel (>= 0.3.0)
    stringex (2.5.2)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    truncate_html (0.9.2)
    ttfunk (1.1.1)
    turbolinks (2.5.3)
      coffee-rails
    twitter_cldr (3.2.1)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0.0)
      json
      tzinfo
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    xml-simple (1.1.5)
    yui-compressor (0.12.0)

PLATFORMS
  ruby

DEPENDENCIES
  asset_sync
  autoprefixer-rails
  aws-sdk-v1
  bower
  braintree
  byebug
  coffee-rails
  figaro
  headjs-rails
  htmlcompressor
  jbuilder
  jquery-rails
  kgio
  mandrill-api
  mysql2
  passenger
  pg
  rack-cache
  rack-zippy
  rails (= 4.2.2)
  rails_12factor
  ransack
  redcarpet
  respond-rails (~> 1.0)
  sass-rails
  sdoc
  spree!
  spree_auth_devise!
  spree_better_terms_and_conditions!
  spree_gateway!
  spree_i18n!
  spree_mail_settings!
  spree_paypal_express!
  spree_print_invoice!
  spree_static_content!
  spring
  sprockets-rails
  turbolinks
  uglifier
  web-console
  yui-compressor

**Comment by niquepa** [comment]
@mmintel  Did you find out the problem? i'm trying to install in heroku and got this:

```
Migrating to AddTranslationsToMainModels (20160216015520)
   (1.8ms)  BEGIN
== 20160216015520 AddTranslationsToMainModels: migrating ======================
   (3.9ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `create_translation_table!' for #<Class:0x007f2c0968fdd0>
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/app/db/migrate/20160216015520_add_translations_to_main_models.spree_i18n.rb:6:in `up'
```

**Comment by alepore** [comment]
yes, on spree 3.1+ the `globalize` integration was extracted from `spree_i18n` to `spree_globalize`

**Comment by aashish** [comment]
After trying
`gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'`

output of `bundle install` is
```
Bundler could not find compatible versions for gem "spree_i18n":
  In Gemfile:
    spree_i18n

    spree_globalize was resolved to 3.1.0.beta, which depends on
      spree_i18n (~> 3.1.0.beta)
```

**Comment by niquepa** [comment]
@aashish What spree version are you installing?

**Comment by aashish** [comment]
@niquepa     spree version 3.2.0
