### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by chris-barklem** [spree-contrib/spree_i18n#677]
Bundle install fails with versioning:

```
| => bundle update
Fetching git://github.com/spree-contrib/spree_i18n.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_i18n was resolved to 3.2.0.alpha, which depends on
      spree_core (~> 3.2.0.alpha)

Could not find gem 'spree_core (~> 3.2.0.alpha)', which is required by gem 'spree_i18n', in any of the sources.
```

I have tried downing the spree_i18n gem to see if I can get and non-conflicting match.

```
Using spree_core 3.1.0.rc3
Using spree_auth_devise 3.1.0
Using spree_gateway 3.1.0
Using spree_i18n 3.1.0 from git://github.com/spree-contrib/spree_i18n.git (at 3-1-stable@5933cda)
```

Works as a stable set of gem versions, but the command with the following in the gemfile:

```
gem 'spree'
gem 'spree_auth_devise'
gem 'spree_gateway'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-1-stable'
```

So with no conflicting versions, the install command fails: 

bundle exec rails g spree_i18n:install
Fails with this:
```

| ~/projects/mundodelte @ Chris-Mac (chris) 
| => rails g spree_i18n:install
/Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-5933cda5bfd8/lib/spree_i18n.rb:3:in `require': cannot load such file -- spree_core (LoadError)
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-5933cda5bfd8/lib/spree_i18n.rb:3:in `<top (required)>'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `require'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `each'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `block in require'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `each'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `require'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler.rb:102:in `require'
	from /Users/chris/projects/mundodelte/config/application.rb:7:in `<top (required)>'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `require'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `preload'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/chris/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by damianlegawiec** [comment]
@chris-barklem check the updated `README.md` https://github.com/spree-contrib/spree_i18n#installation
