### ISSUE TITLE
Works in development but not in production

### ISSUE THREAD

**Issue by bnymn** [spree-contrib/spree_i18n#715]
Hi!

I followed the instructions to install spree_i18n in [project home page](https://github.com/spree-contrib/spree_i18n).

When I start my application with **rails server -e development**, there is no problem, it works. But when I try **rails server -e production**, I get the following errors:

```
/home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-ec7686e11f0b/lib/generators/spree_i18n/install/install_generator.rb:3:in `<module:Generators>': uninitialized constant Generators::Base (NameError)
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-ec7686e11f0b/lib/generators/spree_i18n/install/install_generator.rb:2:in `<module:SpreeI18n>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-ec7686e11f0b/lib/generators/spree_i18n/install/install_generator.rb:1:in `<top (required)>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:471:in `each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:471:in `block in eager_load!'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:469:in `each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:469:in `eager_load!'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:346:in `eager_load!'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:56:in `each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /ssd/Projects/spree-otel/config/environment.rb:5:in `<top (required)>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /ssd/Projects/spree-otel/config.ru:3:in `block in <main>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /ssd/Projects/spree-otel/config.ru:in `new'
	from /ssd/Projects/spree-otel/config.ru:in `<main>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:272:in `start'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /ssd/Projects/spree-otel/bin/rails:9:in `require'
	from /ssd/Projects/spree-otel/bin/rails:9:in `<top (required)>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/bunyamin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /ssd/Projects/spree-otel/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

```

Here is my **Gemfile**:

```
source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
gem 'puma'

# Spree
gem 'spree', '~> 3.1.0.rc1'
gem 'spree_auth_devise', '~> 3.1.0.rc1'
gem 'spree_gateway', '~> 3.1.0.rc1'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'

# Simple, Heroku-friendly Rails app configuration using ENV and a single YAML file
gem 'figaro'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # Capistrano
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-rbenv'
  gem 'capistrano3-puma'
end
```

Here is my **Gemfile.lock** file:

```
GIT
  remote: git://github.com/spree-contrib/spree_i18n.git
  revision: ec7686e11f0be659cf30061b29175f5d403611e5
  specs:
    spree_i18n (3.2.0.alpha)
      i18n_data
      kaminari-i18n
      rails-i18n
      routing-filter
      spree_core (>= 3.1.0, < 4.0)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7.1)
      actionview (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7.1)
      activesupport (= 4.2.7.1)
      globalid (>= 0.3.0)
    activemerchant (1.64.0)
      activesupport (>= 3.2.14, < 5.1)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
    activerecord (4.2.7.1)
      activemodel (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      arel (~> 6.0)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_list (0.7.2)
      activerecord (>= 3.0)
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    airbrussh (1.1.2)
      sshkit (>= 1.6.1, != 1.7.0)
    arel (6.0.4)
    autoprefixer-rails (6.7.6)
      execjs
    awesome_nested_set (3.0.3)
      activerecord (>= 4.0.0, < 5)
    bcrypt (3.1.11)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    builder (3.2.3)
    byebug (9.0.6)
    camertron-eprun (1.1.1)
    cancancan (1.10.1)
    canonical-rails (0.0.11)
      rails (>= 3.1, < 5.0)
    capistrano (3.8.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-rails (1.2.3)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rbenv (2.1.0)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capistrano3-puma (1.2.1)
      capistrano (~> 3.0)
      puma (>= 2.6)
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    cldr-plurals-runtime-rb (1.0.1)
    climate_control (0.1.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    colorize (0.8.1)
    concurrent-ruby (1.0.5)
    css_parser (1.4.10)
      addressable
    debug_inspector (0.0.2)
    deface (1.0.2)
      colorize (>= 0.5.8)
      nokogiri (~> 1.6.0)
      polyglot
      rails (>= 3.1)
    devise (3.5.10)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    erubis (2.7.0)
    execjs (2.7.0)
    ffaker (2.2.0)
    figaro (1.1.1)
      thor (~> 0.14)
    font-awesome-rails (4.7.0.1)
      railties (>= 3.2, < 5.1)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    highline (1.6.21)
    htmlentities (4.3.4)
    i18n (0.8.1)
    i18n_data (0.7.0)
    jbuilder (2.6.3)
      activesupport (>= 3.0.0, < 5.2)
      multi_json (~> 1.2)
    jquery-rails (4.2.2)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.6)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kaminari-i18n (0.4.0)
      kaminari
      rails
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.0)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    monetize (1.6.0)
      money (~> 6.8)
    money (6.8.2)
      i18n (>= 0.6.4, < 0.9)
      sixarm_ruby_unaccent (>= 1.1.1, < 2)
    multi_json (1.12.1)
    mysql2 (0.4.5)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (4.1.0)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    orm_adapter (0.5.0)
    paperclip (4.3.7)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    paranoia (2.1.5)
      activerecord (~> 4.0)
    polyamorous (1.3.1)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    premailer (1.10.2)
      addressable
      css_parser (>= 1.4.10)
      htmlentities (>= 4.0.0)
    premailer-rails (1.9.5)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    public_suffix (2.0.5)
    puma (3.8.1)
    rabl (0.12.0)
      activesupport (>= 2.3.14)
    rack (1.6.5)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7.1)
      actionmailer (= 4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      activemodel (= 4.2.7.1)
      activerecord (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-i18n (4.0.9)
      i18n (~> 0.7)
      railties (~> 4.0)
    railties (4.2.7.1)
      actionpack (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rdoc (4.3.0)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    routing-filter (0.6.0)
      actionpack (>= 4.2, < 5.1)
      activesupport (>= 4.2, < 5.1)
    sass (3.4.23)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    sixarm_ruby_unaccent (1.1.1)
    spree (3.1.3)
      spree_api (= 3.1.3)
      spree_backend (= 3.1.3)
      spree_cmd (= 3.1.3)
      spree_core (= 3.1.3)
      spree_frontend (= 3.1.3)
      spree_sample (= 3.1.3)
    spree_api (3.1.3)
      rabl (~> 0.12.0)
      spree_core (= 3.1.3)
      versioncake (~> 2.3.1)
    spree_auth_devise (3.1.0)
      devise (~> 3.5.4)
      devise-encryptable (= 0.1.2)
      spree_core (~> 3.1.0.beta)
    spree_backend (3.1.3)
      bootstrap-sass (~> 3.3)
      jquery-rails (~> 4.1)
      jquery-ui-rails (~> 5.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.1.3)
      spree_core (= 3.1.3)
    spree_cmd (3.1.3)
      thor (~> 0.14)
    spree_core (3.1.3)
      activemerchant (~> 1.59)
      acts_as_list (= 0.7.2)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 2.2.0)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      kaminari (~> 0.17)
      monetize (~> 1.1)
      paperclip (~> 4.3.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.2.5)
      ransack (~> 1.4.1)
      responders
      sprockets-rails
      state_machines-activerecord (~> 0.2)
      stringex
      truncate_html (~> 0.9.3)
      twitter_cldr (~> 3.0)
    spree_frontend (3.1.3)
      bootstrap-sass (>= 3.3.5.1, < 3.4)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 4.1)
      spree_api (= 3.1.3)
      spree_core (= 3.1.3)
    spree_gateway (3.1.0)
      spree_core (~> 3.1.0.beta)
    spree_sample (3.1.3)
      spree_core (= 3.1.3)
    spring (2.0.1)
      activesupport (>= 4.2)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.12.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    state_machines (0.4.0)
    state_machines-activemodel (0.4.0)
      activemodel (>= 4.1, < 5.1)
      state_machines (>= 0.4.0)
    state_machines-activerecord (0.4.0)
      activerecord (>= 4.1, < 5.1)
      state_machines-activemodel (>= 0.3.0)
    stringex (2.7.1)
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.6)
    truncate_html (0.9.3)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.0)
    twitter_cldr (3.6.0)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0)
      tzinfo
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.1.6)
      execjs (>= 0.3.0, < 3)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.7)
      rack (>= 1.0)
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  bcrypt (~> 3.1.7)
  byebug
  capistrano
  capistrano-bundler
  capistrano-rails
  capistrano-rbenv
  capistrano3-puma
  coffee-rails (~> 4.1.0)
  figaro
  jbuilder (~> 2.0)
  jquery-rails
  mysql2 (>= 0.3.13, < 0.5)
  puma
  rails (= 4.2.7.1)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spree (~> 3.1.0.rc1)
  spree_auth_devise (~> 3.1.0.rc1)
  spree_gateway (~> 3.1.0.rc1)
  spree_i18n!
  spring
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.13.7

```

**Comment by bnymn** [comment]
The problem is solved when I used **3-1-stable** branch. Appearently 3-2-alpha branch requires Rails 5.0, which is not installed in my setup.

`gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-1-stable'`
