### ISSUE TITLE
Could not find generator 'spree_i18n:install'

### ISSUE THREAD

**Issue by D7na** [spree-contrib/spree_i18n#717]
Using Ruby 2.4.0, Rails 5.0.2, Spree 3.2.0

In Gemfile:
```
gem 'spree', '~> 3.2.0'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
```
"bundle exec rails g spree_i18n:install" after "bundle install" causes the following error:

Running via Spring preloader in process 24864
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator 'spree_i18n:install'. Maybe you meant 'spree:auth:install', 'spree:install' or 'spree_gateway:install'
Run `rails generate --help` for more options.

**Comment by symarys** [comment]
Hi @D7na! I'm trying to reproduce your issue with the same dependencies (Ruby 2.4.0, Rails 5.0.2, Spree 3.2.0) and I'm not getting any errors while executing `bundle exec rails g spree_i18n:install`. Can you provide us with more details, based on the draft below?

## Steps to Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue include code to reproduce, if relevant
1.
2.
3.
4.

## Your Environment
Include as many relevant details about the environment you experienced the issue in
* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by HaoRuby** [comment]
I get same problem.
Here is my environment infomation:

- Rails version: 4.2.6

- Spree version: 3.1

- Logs



![screenshot from 2017-04-03 15-40-20](https://cloud.githubusercontent.com/assets/25974999/24601781/7036c630-1884-11e7-99b6-467ece9768d4.png)

**Comment by clevertechru** [comment]
Hello. I have this problem too, on production, not development

**Comment by clevertechru** [comment]
OMG, new info:
for RAILS_ENV=development - OK
for RAILS_ENV=production - Fail

```
$ RAILS_ENV=development bundle exec rails g spree_i18n:install
Running via Spring preloader in process 31266
      append  vendor/assets/javascripts/spree/backend/all.js
      append  vendor/assets/javascripts/spree/frontend/all.js
         run  bundle exec rake railties:install:migrations FROM=spree_i18n from "."
         run  bundle exec rake db:migrate from "."
```

```
$ RAILS_ENV=production bundle exec rails g spree_i18n:install
/home/production/.rvm/gems/ruby-2.2.5/bundler/gems/spree_i18n-07f2b0ff4a09/lib/generators/spree_i18n/install/install_generator.rb:3:in `<module:Generators>': uninitialized constant Generators::Base (NameError)
	from /home/production/.rvm/gems/ruby-2.2.5/bundler/gems/spree_i18n-07f2b0ff4a09/lib/generators/spree_i18n/install/install_generator.rb:2:in `<module:SpreeI18n>'
	from /home/production/.rvm/gems/ruby-2.2.5/bundler/gems/spree_i18n-07f2b0ff4a09/lib/generators/spree_i18n/install/install_generator.rb:1:in `<top (required)>'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/engine.rb:471:in `each'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/engine.rb:471:in `block in eager_load!'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/engine.rb:469:in `each'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/engine.rb:469:in `eager_load!'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/engine.rb:346:in `eager_load!'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:56:in `each'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /var/www/dev.lidermed.ru/releases/first/config/environment.rb:5:in `<top (required)>'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /home/production/.rvm/gems/ruby-2.2.5/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/production/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by clevertechru** [comment]
Fixed: add require 'rails/generators' after require 'rails/all' to config/application.rb
